---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app: producer
  replicas: 160 
  template:
    metadata:
      labels:
        app: producer
    spec:
      nodeSelector:
        agentpool: np001
      containers:
      - name: producer
        image: 605125156525.dkr.ecr.ap-southeast-1.amazonaws.com/load-tester:0.0.32
        imagePullPolicy: IfNotPresent
        env:
        - name: NUM_JOBS
          value: "200"
        - name: NUM_WORKERS
          value: "200"
        - name: KAFKA_BROKER1_ADDRESS
          value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER2_ADDRESS
          value: "kafka-1.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER3_ADDRESS
          value: "kafka-2.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER4_ADDRESS
          value: "kafka-3.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER5_ADDRESS
          value: "kafka-4.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER6_ADDRESS
          value: "kafka-5.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER7_ADDRESS
          value: "kafka-6.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER8_ADDRESS
          value: "kafka-7.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER9_ADDRESS
          value: "kafka-8.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER10_ADDRESS
          value: "kafka-9.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER11_ADDRESS
          value: "kafka-10.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER12_ADDRESS
          value: "kafka-11.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER13_ADDRESS
          value: "kafka-12.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER14_ADDRESS
          value: "kafka-13.kafka-headless.kafka.svc.cluster.local:9092"
        - name: REDIS_MASTER_ADDRESS
          value: "ragnarok-redis-master.ragnarok.svc.cluster.local:6379"
        - name: REDIS_REPLICA_ADDRESS
          value: "ragnarok-redis-replicas.ragnarok.svc.cluster.local:6379"
        - name: REDIS_PASS
          value: "1PIyhJfjbu"
        - name: CONSUMER_GROUP
          value: "cg002"
        - name: DATA_SOURCE_DIRECTORY
          value: "/datastore"
        - name: DATA_OUT_DIRECTORY
          value: "/processed"
        - name: LOCAL_LOGFILE_PATH
          value: "/applogs"
        - name: MESSAGE_TOPIC
          value: "messages"
        - name: DEADLETTER_TOPIC
          value: "deadLetter"
        - name: METRICS_TOPIC
          value: "metrics"      
        - name: METRICS_PORT_NUMBER
          value: "80"
        volumeMounts:
          - name: applogs
            mountPath: /applogs
          - name: backups
            mountPath: /backups
        ports:
          - name: tcp-80
            containerPort: 80
      volumes:
        - name: applogs
          persistentVolumeClaim:
            claimName: applogs-claim
        - name: backups
          persistentVolumeClaim:
            claimName: backups-claim
      imagePullSecrets:
        - name: ragnarok

---
kind: Service
apiVersion: v1
metadata:
  name: producer-service
  namespace: ragnarok
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - name: tcp-80
      port: 80
      nodePort: 30082
      protocol: TCP
