{
 "title": "Transaction Matching System Load Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Producer Pool Load GenerationMetrics",
   "type": "timeseries",
   "description": "Metrics indicating the Load Generation performance of the producer pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(load_producer_failed_requests_total[1m])",
     "legendFormat": "failed requests per minute"
    },
    {
     "expr": "rate(load_producer_input_requests_total[1m])",
     "legendFormat": "input requests per minute"
    },
    {
     "expr": "rate(load_producer_submit_requests_total[1m])",
     "legendFormat": "submitted requests per minute"
    }
   ]
  },
  {
   "title": "Producer Pool Concurrency Metrics",
   "type": "timeseries",
   "description": "Concurrent Workers and Jobs for the producer pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "load_producer_concurrent_workers{}"
    },
    {
     "expr": "load_producer_concurrent_jobs{}"
    }
   ]
  },
  {
   "title": "Consumer Pool Load Generation Metrics",
   "type": "timeseries",
   "description": "Requests consumed from the load message queue vs. requests failed to post to the target api",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(load_consumer_consumed_requests_total[1m])",
     "legendFormat": "consumed requests per minute"
    },
    {
     "expr": "rate(load_consumer_failed_requests_total[1m])",
     "legendFormat": "request consume failures per minute"
    },
    {
     "expr": "rate(load_consumer_successul_requests_total[1m])",
     "legendFormat": "successfully posted requests per minute"
    }
   ]
  },
  {
   "title": "Worker Pool Concurrency Metrics",
   "type": "timeseries",
   "description": "Concurrent Worker and Job count per Worker pool instance of Golang",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "load_consumer_concurrent_jobs{}"
    },
    {
     "expr": "load_consumer_concurrent_workers{}"
    }
   ]
  },
  {
   "title": "Target Application Load Metrics (Volume)",
   "type": "timeseries",
   "description": "Inbound Request Load Statistics for Target Application",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "loadsink_failed_requests_total{}"
    },
    {
     "expr": "loadsink_successul_requests_total{}"
    }
   ]
  },
  {
   "title": "Target System Load Metrics (Rate)",
   "type": "timeseries",
   "description": "Load Metrics of the System under Load Testing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(loadsink_failed_requests_total[1m])",
     "legendFormat": "loadsink_failed_requests per minute"
    },
    {
     "expr": "rate(loadsink_successul_requests_total[1m])",
     "legendFormat": "oadsink_successul_requests per minute"
    }
   ]
  },
  {
   "title": "Input File Generator Metrics (volumes)",
   "type": "timeseries",
   "description": "Input Request file generation and error metrics for the input file loader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "load_files_generated_total{}" },
    { "expr": "load_files_errors_total{}" }
   ]
  },
  {
   "title": "Input File Generator Metrics (rates)",
   "type": "timeseries",
   "description": "Input file generation rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(load_files_generated_total[1m])",
     "legendFormat": "input files generated per minute"
    }
   ]
  }
 ]
}