---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: output-claim
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consumerapplogs-claim
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 160
  template:
    metadata:
      labels:
        app: consumer
    spec:
      nodeSelector:
        agentpool: np003
      containers:
      - name: consumer
        image: 605125156525.dkr.ecr.ap-southeast-1.amazonaws.com/load-consumer:0.0.35
        imagePullPolicy: IfNotPresent
        env:
        - name: NUM_JOBS
          value: "200"
        - name: NUM_WORKERS
          value: "200"
        - name: KAFKA_BROKER1_ADDRESS
          value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER2_ADDRESS
          value: "kafka-1.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER3_ADDRESS
          value: "kafka-2.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER4_ADDRESS
          value: "kafka-3.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER5_ADDRESS
          value: "kafka-4.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER6_ADDRESS
          value: "kafka-5.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER7_ADDRESS
          value: "kafka-6.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER8_ADDRESS
          value: "kafka-7.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER9_ADDRESS
          value: "kafka-8.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER10_ADDRESS
          value: "kafka-9.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER11_ADDRESS
          value: "kafka-10.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER12_ADDRESS
          value: "kafka-11.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER13_ADDRESS
          value: "kafka-12.kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER14_ADDRESS
          value: "kafka-13.kafka-headless.kafka.svc.cluster.local:9092"
        - name: CONSUMER_GROUP
          value: "cg001"
        - name: CONSUMER_COMMIT_INTERVAL
          value: "1"
        - name: LOCAL_LOGFILE_PATH
          value: "/applogs"
        - name: MESSAGE_TOPIC
          value: "messages"
        - name: DEADLETTER_TOPIC
          value: "deadLetter"
        - name: METRICS_TOPIC
          value: "metrics"      
        - name: TARGET_API_URL
          value: "http://sink-service.ragnarok.svc.cluster.local/sink-orders"
        - name: PORT_NUMBER
          value: "80"
        ports:
          - name: tcp-80
            containerPort: 80
        volumeMounts:
          - name: applogs
            mountPath: /applogs
          - name: output
            mountPath: /output-api
      volumes:
        - name: applogs
          persistentVolumeClaim:
            claimName: consumerapplogs-claim
        - name: output
          persistentVolumeClaim:
            claimName: output-claim
      imagePullSecrets:
        - name: ragnarok

---

kind: Service
apiVersion: v1
metadata:
  name: consumer-service
  namespace: ragnarok
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    - name: tcp-80
      port: 80
      nodePort: 30081
      protocol: TCP
