apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: ragnarok
rules:
  - apiGroups: [""]
    resources:
      - pods
      - deployments
    verbs:
      - get
      - list
      - delete
