---
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
  namespace: ragnarok
spec:
  selector:
    app: nfs-server
  ports:
    # Open the ports required by the NFS server
    # Port 2049 for TCP
    - name: tcp-2049
      port: 2049
      protocol: TCP
