kind: Pod
apiVersion: v1
metadata:
  name: nfs-client
  namespace: ragnarok
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-volume
      nfs: 
        # URL for the NFS server
        server: 10.42.0.238 #Change this to the current address of the NFS service
        path: /mnt
  # In this container, we'll mount the NFS volume
  # and write the date to a file inside it.
  containers:
    - name: dataclient 
      image: gcr.io/google_containers/volume-nfs:0.8 
      #image: alpine
      # Mount the NFS volume in the container
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt
      # Write a heartbeat to a file inside our NFS as confirmation we're alive
      #command: ["/bin/sh"]
      #args: ["-c", "while true; do date >> /var/log/nfs-heartbeat.log; sleep 5; done"]
      securityContext:
        privileged: true
