apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim 
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
